###Test index
GET http://localhost:5000


###
### Admin's api
###

### Git latest 10 conversations and the last message of every conversastion
GET http://localhost:5000/api/admin/firstget


###Git more latest 10 conversations
GET http://localhost:5000/api/admin/moreconversations

###Login - If the user doesn't have the token -- or his token is wrong
POST http://localhost:5000/api/admin/login HTTP/1.1
content-type: application/json
{
    "username" : "test",
    "password" : "tt"
}

###
###clinet's api -- (One user and all admins can get this by special-tonken)
###

###When the first get - get the last messages (document of last chat) if the user has already the token id in his storage
GET http://localhost:5000/api/client/lastchatdoc

### We need to send the current id of chat-document to get the prev chat-document
GET http://localhost:5000/api/client/prevchatdoc


###To create a session - create and return the token. If the user doesn't has the token in his storage / POST
POST http://localhost:5000/api/client/startsession HTTP/1.1
content-type: application/json
{
    "id" : "60ea0ac277033e44a47fd5e8",
    "token" : "5e6l6o7qbflrylc0v055t"
}